/* INSERT */

INSERT INTO game_modes (id_game_modes, name) VALUES
(0, 'game_mode_unknown'),
(1, 'game_mode_all_pick'),
(2, 'game_mode_captains_mode'),
(3, 'game_mode_random_draft'),
(4, 'game_mode_single_draft'),
(5, 'game_mode_all_random'),
(6, 'game_mode_intro'),
(7, 'game_mode_diretide'),
(8, 'game_mode_reverse_captains_mode'),
(9, 'game_mode_greeviling'),
(10, 'game_mode_tutorial'),
(11, 'game_mode_mid_only'),
(12, 'game_mode_least_played'),
(13, 'game_mode_limited_heroes'),
(14, 'game_mode_compendium_matchmaking'),
(15, 'game_mode_custom'),
(16, 'game_mode_captains_draft'),
(17, 'game_mode_balanced_draft'),
(18, 'game_mode_ability_draft'),
(19, 'game_mode_event'),
(20, 'game_mode_all_random_death_match'),
(21, 'game_mode_1v1_mid'),
(22, 'game_mode_all_draft'),
(23, 'game_mode_turbo'),
(24, 'game_mode_mutation'),
(25, 'game_mode_coaches_challenge');

INSERT INTO Heroes (id_heroes, name) VALUES
(1, 'Anti-Mage'),
(2, 'Axe'),
(3, 'Bane'),
(4, 'Bloodseeker'),
(5, 'Crystal Maiden'),
(6, 'Drow Ranger'),
(7, 'Earthshaker'),
(8, 'Juggernaut'),
(9, 'Mirana'),
(10, 'Morphling'),
(11, 'Shadow Fiend'),
(12, 'Phantom Lancer'),
(13, 'Puck'),
(14, 'Pudge'),
(15, 'Razor'),
(16, 'Sand King'),
(17, 'Storm Spirit'),
(18, 'Sven'),
(19, 'Tiny'),
(20, 'Vengeful Spirit'),
(21, 'Windranger'),
(22, 'Zeus'),
(23, 'Kunkka'),
(25, 'Lina'),
(26, 'Lion'),
(27, 'Shadow Shaman'),
(28, 'Slardar'),
(29, 'Tidehunter'),
(30, 'Witch Doctor'),
(31, 'Lich'),
(32, 'Riki'),
(33, 'Enigma'),
(34, 'Tinker'),
(35, 'Sniper'),
(36, 'Necrophos'),
(37, 'Warlock'),
(38, 'Beastmaster'),
(39, 'Queen of Pain'),
(40, 'Venomancer'),
(41, 'Faceless Void'),
(42, 'Skeleton King'),
(43, 'Death Prophet'),
(44, 'Phantom Assassin'),
(45, 'Pugna'),
(46, 'Templar Assassin'),
(47, 'Viper'),
(48, 'Luna'),
(49, 'Dragon Knight'),
(50, 'Dazzle'),
(51, 'Clockwerk'),
(52, 'Leshrac'),
(53, 'Nature''s Prophet'),
(54, 'Lifestealer'),
(55, 'Dark Seer'),
(56, 'Clinkz'),
(57, 'Omniknight'),
(58, 'Enchantress'),
(59, 'Huskar'),
(60, 'Night Stalker'),
(61, 'Broodmother'),
(62, 'Bounty Hunter'),
(63, 'Weaver'),
(64, 'Jakiro'),
(65, 'Batrider'),
(66, 'Chen'),
(67, 'Spectre'),
(68, 'Ancient Apparition'),
(69, 'Doom'),
(70, 'Ursa'),
(71, 'Spirit Breaker'),
(72, 'Gyrocopter'),
(73, 'Alchemist'),
(74, 'Invoker'),
(75, 'Silencer'),
(76, 'Outworld Devourer'),
(77, 'Lycanthrope'),
(78, 'Brewmaster'),
(79, 'Shadow Demon'),
(80, 'Lone Druid'),
(81, 'Chaos Knight'),
(82, 'Meepo'),
(83, 'Treant Protector'),
(84, 'Ogre Magi'),
(85, 'Undying'),
(86, 'Rubick'),
(87, 'Disruptor'),
(88, 'Nyx Assassin'),
(89, 'Naga Siren'),
(90, 'Keeper of the Light'),
(91, 'Wisp'),
(92, 'Visage'),
(93, 'Slark'),
(94, 'Medusa'),
(95, 'Troll Warlord'),
(96, 'Centaur Warrunner'),
(97, 'Magnus'),
(98, 'Timbersaw'),
(99, 'Bristleback'),
(100, 'Tusk'),
(101, 'Skywrath Mage'),
(102, 'Abaddon'),
(103, 'Elder Titan'),
(104, 'Legion Commander'),
(105, 'Techies'),
(106, 'Ember Spirit'),
(107, 'Earth Spirit'),
(108, 'Abyssal Underlord'),
(109, 'Terrorblade'),
(110, 'Phoenix'),
(111, 'Oracle'),
(112, 'Winter Wyvern'),
(113, 'Arc Warden'),
(114, 'Monkey King'),
(119, 'Dark Willow'),
(120, 'Pangolier'),
(121, 'Grimstroke'),
(123, 'Hoodwink'),
(126, 'Void Spirit'),
(128, 'Snapfire'),
(129, 'Mars'),
(131, 'Ringmaster'),
(135, 'Dawnbreaker'),
(136, 'Marci'),
(137, 'Primal Beast'),
(138, 'Muerta'),
(145, 'Kez');

