/* insert pro */
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (365939353, 'Mishito', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (455204409, 'JR', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (118882882, 'WASON-你父亲', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (387633288, 'Z', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (167243895, 'Rayleigh', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (385524445, 'Invencible', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1212124835, 'SuportSitorio', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1163176065, 'FuNsito', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (436233591, 'FIFi', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (137269978, 'XdLink', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1712893556, 'Justice / Pos 4/5', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (957136986, '♱ⱤƳⱿƸⱤ♱', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1401495297, 'Стрелок ГОДА', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1505310182, 'Long Live Achaemenid', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (149656433, '1', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1424106148, 'largon', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1876026910, 'ko1zzz', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1863035151, 'remir', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (155026476, 'SIPI', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1901670663, 'говори́т', 0) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1017876764, 'テlet me dieテ SSS zxc KING', 9088071) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1029972951, 'Aomine~', 9593609) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (113923026, 'Leocouk', 9088071) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (878549965, 'empty', 9593609) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (314272971, 'shadow warrior', 9593609) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1674266188, 'ФУТБАЛИСТ', 9088071) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (130433320, 'fv', 9088071) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1712916118, 'кр в 7 лёгенько', 9593609) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1695617010, 'Yuui', 9593609) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1023487276, 'ЭЩКЕРЕЕЕ enjoyer', 9088071) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (140592407, 'E$cargot', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (158511758, 'Vex', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (141414763, 'mode prime luqy (160 ping)', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (492401757, 'Deaths Kiss', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (241778294, 'KiNg', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (164474221, 'Бураз Yo$hi', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (420088832, 'RuskDaddy', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (893449828, 'Chill guy who dont distract', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (55012505, 'BreezyR', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (41364162, 'ollamh', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (318286721, 'suuuuuuweyyyy', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1014443978, 'FTT', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (360648679, 'win only', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1125296112, 'hell of a week', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (164991531, 'GG', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (227657377, '球球', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (318371533, 'bear', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (347524932, 'M0nesy', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (136737280, 'XCTN TINO', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (191458152, 'ปลาโลมาน้อ', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1068676453, 'Aboba', 9426115) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (176158708, 'Denz', 9426115) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (412910858, 'Vahee', 9426115) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1194935883, 'Diamond', 8629324) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1090568489, 'SectumSempra', 9426115) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (230308002, 'Doobie', 8629324) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1173255449, 'Pelfox', 8629324) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1133046148, 'billyH', 8629324) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (76082922, 'Melnik', 8629324) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (183270733, 'wannacoffee', 9426115) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (861609952, 'K1rbi', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1419164601, 'rpuwok', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1423247660, 'Charliss', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1422863018, 'ShyChild', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1423033584, 'Trick_K', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (434993584, 'Dreadlight', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1547731378, 'Lightcrawler', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1547080535, 'Shark', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1547582222, 'Qimusavoz', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1547656456, 'livesey', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;

INSERT INTO pro (id_steam, pseudo, id_team) VALUES (365939353, 'Mishito', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (455204409, 'JR', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (118882882, 'WASON-你父亲', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (387633288, 'Z', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (167243895, 'Rayleigh', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (385524445, 'Invencible', 7233359) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1212124835, 'SuportSitorio', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1163176065, 'FuNsito', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (436233591, 'FIFi', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (137269978, 'XdLink', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1486168224, 'Jarom', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (122800667, 'Boo', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (138304602, 'Lillard', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1505310182, 'Long Live Achaemenid', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1323623219, 'Samurai', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (897643094, 'InS4Ne', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (370485183, 'nop', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1702634598, 'hajjichopper', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (259393305, 'Pulse', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (146758513, 'Arsenal1914', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1317149903, 'Kitler', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (118143433, 'Blade', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (441308000, 'йоу', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1876348951, 'Letronis', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1030700012, 'Castellan', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (423372876, 'Atlantis', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (257205019, '.', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1794924166, 'amohaghi', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (436679285, 'Eta', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (128912835, 'below monkey iq owner', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1664048844, 'b1nGo', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (130394345, 'AHTOXA', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (200845941, 'NASVAY 0% NICOTINE', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1393580216, 'quqve', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (149656433, '1', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1863035151, 'remir', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1087410968, '0===()::::Roronoa Zoro::::>', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (838314446, '1234', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1712893556, 'Justice / Pos 4/5', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (160212190, 'ॐ', None) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (164991531, 'GG', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (318371533, 'bear', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (347524932, 'M0nesy', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (227657377, '球球', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (360648679, 'win only', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1014443978, 'FTT', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1125296112, 'hell of a week', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (136737280, 'XCTN TINO', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (318286721, 'suuuuuuweyyyy', 9546449) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (191458152, 'ปลาโลมาน้อ', 9774147) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (861609952, 'K1rbi', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1423033584, 'Trick_K', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1547731378, 'Lightcrawler', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1422863018, 'ShyChild', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1423247660, 'Charliss', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1547656456, 'livesey', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1547582222, 'Qimusavoz', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (434993584, 'Dreadlight', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1547080535, 'Shark', 9339714) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1419164601, 'rpuwok', 8969895) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1499724758, 'Neutron', 8961813) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1669583127, 'RHye', 9332069) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1669300091, 'Evv', 9332069) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1499780198, 'JAM', 8961813) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1670825435, 'Geoman', 9332069) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1499784859, 'heinz', 8961813) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1669449384, 'Ungreat', 9332069) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1499558722, 'Nlainara', 8961813) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1669730945, 'KeanlinS', 9332069) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1525150785, 'Xarientoc', 8961813) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (140592407, 'E$cargot', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (158511758, 'Vex', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (141414763, 'mode prime luqy (160 ping)', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (492401757, 'Deaths Kiss', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (241778294, 'KiNg', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (164474221, 'Бураз Yo$hi', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (420088832, 'RuskDaddy', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (893449828, 'Chill guy who dont distract', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (55012505, 'BreezyR', 8740986) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (41364162, 'ollamh', 9728739) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1061061704, 're', 9264834) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1232094007, 'Nightfull', 8629315) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (992327405, 'Dust_2', 8629315) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (181339278, 'Pudre', 2443375) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (202984325, 'EmbraceTheLight', 8629315) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (162724090, 'Sandy', 8629315) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (80599925, 'Exterminator', 2443375) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (301477244, 'ShinraTensei', 2443375) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1045494300, 'babyface', 2443375) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1103355581, 'titik', 2443375) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;
INSERT INTO pro (id_steam, pseudo, id_team) VALUES (1170923497, 'AKID', 8629315) ON CONFLICT (id_steam) DO UPDATE SET pseudo = EXCLUDED.pseudo, id_team = EXCLUDED.id_team;